#!/usr/bin/env bash
# Operant one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/tomascupr/operant/v0.6.0/install.sh | bash
#
# Pulls the official GHCR images, generates a .env with fresh random secrets
# (no "change-me" footguns), and boots Postgres + the control plane + the
# OpenClaw gateway. Re-running is safe: an existing .env is reused, never
# overwritten.
#
# Knobs (all optional, via environment):
#   OPERANT_DIR        target directory                 (default ./operant)
#   OPERANT_VERSION    image tag to pull                (default 0.6.0)
#   OPERANT_REF        git ref to fetch files from      (default v0.6.0)
#   OPERANT_HTTP_PORT  host port for the dashboard      (default 8080)
#   OPERANT_NO_START   set to 1 to write files but not `docker compose up`
#   OPERANT_SRC_DIR    copy files from a local checkout instead of curl
set -euo pipefail

OPERANT_DIR="${OPERANT_DIR:-operant}"
OPERANT_VERSION="${OPERANT_VERSION:-0.6.0}"
OPERANT_REF="${OPERANT_REF:-v0.6.0}"
OPERANT_HTTP_PORT="${OPERANT_HTTP_PORT:-8080}"
OPERANT_NO_START="${OPERANT_NO_START:-0}"
OPERANT_SRC_DIR="${OPERANT_SRC_DIR:-}"
RAW_BASE="https://raw.githubusercontent.com/tomascupr/operant/${OPERANT_REF}"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
info() { printf '  %s\n' "$1"; }
die() { printf '\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }

# Fetch a repo-relative file into a destination path. Uses a local checkout
# when OPERANT_SRC_DIR is set (handy for testing/offline), curl otherwise.
fetch() {
  local rel="$1" dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [ -n "$OPERANT_SRC_DIR" ]; then
    cp "$OPERANT_SRC_DIR/$rel" "$dest"
  else
    curl -fsSL "$RAW_BASE/$rel" -o "$dest"
  fi
}

# N random bytes as hex (2N chars). Valid as OPERANT_SECRET_KEY (64-hex = 32
# bytes) and URL-safe for the Postgres password. openssl, or /dev/urandom.
rand() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"
  else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

bold "Operant installer (v${OPERANT_VERSION})"

command -v docker >/dev/null 2>&1 || die "docker is required — install Docker Desktop or Docker Engine first."
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (the 'docker compose' plugin)."

mkdir -p "$OPERANT_DIR"
cd "$OPERANT_DIR"

info "Fetching stack definition into $(pwd) ..."
fetch "docker-compose.quickstart.yml" "docker-compose.yml"
fetch "deploy/openclaw/operant-secret-resolver.mjs" "deploy/openclaw/operant-secret-resolver.mjs"

if [ -f .env ]; then
  info ".env already exists — reusing it (delete it to regenerate secrets)."
else
  info "Generating .env with fresh random secrets ..."
  POSTGRES_PASSWORD="$(rand 24)"
  cat > .env <<EOF
# Generated by install.sh on first run. Treat as secret; do not commit.
OPERANT_VERSION=${OPERANT_VERSION}
OPERANT_HTTP_PORT=${OPERANT_HTTP_PORT}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgres://operant:${POSTGRES_PASSWORD}@postgres:5432/operant

OPERANT_SECRET_KEY=$(rand 32)
OPERANT_INTERNAL_TOKEN=$(rand 24)
OPERANT_ADMIN_LOGIN_TOKEN=$(rand 24)
OPENCLAW_GATEWAY_TOKEN=$(rand 24)
EOF
  chmod 600 .env
fi

if [ "$OPERANT_NO_START" = "1" ]; then
  bold "Files ready in $(pwd) (skipped 'docker compose up' — OPERANT_NO_START=1)."
  exit 0
fi

info "Pulling images and starting the stack ..."
docker compose up -d

ADMIN_TOKEN="$(grep '^OPERANT_ADMIN_LOGIN_TOKEN=' .env | cut -d= -f2-)"
echo
bold "Operant is up."
info "Dashboard:   http://localhost:${OPERANT_HTTP_PORT}"
info "Admin token: ${ADMIN_TOKEN}"
info "Sign in with that token + your Slack member ID (or Teams AAD ID), then"
info "finish credentials on the Setup tab. Stop with: docker compose down"
